
---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook: #use dt_webhook as source for ansible-rulebook 
        host: 0.0.0.0
        port: 5000
        token: '{{ var_eda_token }}' 

  rules:
    - name: Problem payload Dynatrace for DB Failure rate increase issue
      condition: events.m_1.payload.eventData.problemStatus == "OPEN" and (events.m_1.payload.eventData.problemTitle == "Request error rate increase" or events.m_1.payload.eventData.problemTitle == "Failure rate increase")
      action:
        run_job_template:
          name: easytrade-fix-webhook
          organization: "Default"
          job_args:
            extra_vars:
              dt_easytrade_url: '{{ et_url }}'
              dt_api_token: '{{ dt_token }}'
              dt_api_url: '{{ dt_url }}'
